###
# Animals
###
GET http://localhost:7000

###
GET http://localhost:7000/tickets

###
GET http://localhost:7000/animals

###
GET http://localhost:7000/animals/4

###
POST http://localhost:7000/animals
Content-Type: application/json

{
  "name": "Spider",
  "count": 94
}

###
DELETE http://localhost:7000/animals/2

###

PATCH http://localhost:7000/animals/3
Content-Type: application/json

{
  "name": "Cat",
  "count": "1000"
}

###
# Sea critters
###

GET http://localhost:7000/sea-critters

###

GET http://localhost:7000/sea-critters/4

